version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: refla_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: refla
    ports:
      - '5432:5432'
    volumes:
      - refla_pg_data:/var/lib/postgresql/data

volumes:
  refla_pg_data:
